//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblticket()
        {
            this.tbltickethistory = new HashSet<tbltickethistory>();
        }
    
        public int id { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> ticketstatusid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public bool deleted { get; set; }
        public Nullable<int> assignedtoid { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public string comment { get; set; }
    
        public virtual tbldepartment tbldepartment { get; set; }
        public virtual tblticketstatus tblticketstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<tbltickethistory> tbltickethistory { get; set; }
    }
}
