//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketSystemEntities : DbContext
    {
        public TicketSystemEntities()
            : base("name=TicketSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbldepartment> tbldepartments { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<tbltickethistory> tbltickethistories { get; set; }
        public virtual DbSet<tblticket> tbltickets { get; set; }
        public virtual DbSet<tblticketstatu> tblticketstatus { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tbluserdepartment> tbluserdepartments { get; set; }
        public virtual DbSet<tbluserinfo> tbluserinfoes { get; set; }
        public virtual DbSet<tbluserrole> tbluserroles { get; set; }
    }
}
